
services:  
  mysql:  
    image: mysql:latest  
    ports:  
      - "3307:3306"  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: bd  
    restart: "no"  
    environment:  
      MYSQL_ROOT_PASSWORD: 1234  
      MYSQL_DATABASE: db_venda  
      TZ: "America/Bahia"  
      
  spring-app:
    build:
      context: ./venda
      dockerfile: Dockerfile
    container_name: api-venda
    restart: unless-stopped
    ports:
      - "8080:8080"  
    volumes:
      - ./src/main/resources:/app/resources
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bd:3306/db_venda
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      mysql:
        condition: service_healthy

  reportsale:
    build:
      context: ./reportsale
      dockerfile: Dockerfile
    container_name: reportsale
    restart: unless-stopped
    ports:
      - "8081:8081"  
    volumes:
      - ./src/main/resources:/app/resources
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bd:3306/db_venda
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
     - spring-app
